name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Nexus Registry
        uses: docker/login-action@v3
        with:
          registry: docker.nixbug.com
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            docker.nixbug.com/entebus/operator-app:${{ github.sha }}
            docker.nixbug.com/entebus/operator-app:latest
